version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: sudo npm i -g vuepress@0.14.10
      - run: vuepress build
      - run: echo "google-site-verification: google0c12c14bc606ef19.html" > .vuepress/dist/google0c12c14bc606ef19.html
      - run:
          name: deploy
          command: |
            git config --global user.email "huajiejin@qq.com"
            git config --global user.name "huajie"
            git add -f .vuepress/dist
            git commit -m 'deploy from circleci'
            git push origin `git subtree split --prefix .vuepress/dist master`:gh-pages --force
