version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm i vuepress
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: node_modules
      - run: sh deploy.circleci.sh
