version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    filters:
      branches:
        only: master
    steps:
      - checkout
      # - restore_cache:
      #   keys:
      #     - node_modules
      - run: sudo npm i -g vuepress
      - run: ls -alh /usr/local/lib/node_modules
      - run: vuepress -V
      # - save_cache:
      #     paths:
      #       - ~/usr/local/lib/node_modules
      #     key: node_modules
      # - run: sh deploy.circleci.sh
