version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - vuepress-cache
            - vuepress-cache
      - run: sudo npm i -g vuepress
      - save_cache:
          key: vuepress-cache
          paths:
            - /usr/local/lib/node_modules
      - run: sh deploy.circleci.sh
