version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node-v1-v-
            - node-v1-
      - run: npm i vuepress
      - save_cache:
          key: node-v1-v-
          paths: node_modules
      - run: sh deploy.circleci.sh
